FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=development
ENV CONTAINER=true

COPY . . 
COPY openapi ./dist/openapi

RUN npm ci --include=dev  
RUN npm run build 
RUN npm install -g ts-node typescript 
RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]