name: Documentation Improvement
description: Suggest improvements or corrections to the documentation.
title: "[Documentation]: "
labels: ["documentation"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the documentation issue or improvement.
      placeholder: "Enter a brief summary of the documentation issue"
      required: true

  - type: input
    id: current_documentation
    attributes:
      label: Current Documentation
      description: Provide a link or reference to the current documentation that needs improvement.
      placeholder: "Link to the current documentation"

  - type: input
    id: suggested_improvement
    attributes:
      label: Suggested Improvement
      description: Describe how you think the documentation can be improved.
      placeholder: "What changes do you suggest?"
