name: Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature]: "
labels: ["feature"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the proposed feature.
      placeholder: "Enter a brief summary of the feature"
    validations:
      required: true

  - type: textarea
    id: linked_issues
    attributes:
      label: Linked Issues
      description: Reference any related issues or pull requests.
      placeholder: "Link any related issues or PRs"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Provide any additional information or context that may help.
      placeholder: "Any other relevant information or links"
