name: Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature]: "
labels: ["feature"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the proposed feature.
      placeholder: "Enter a brief summary of the feature"
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature is needed.
      placeholder: "Why is this feature important?"

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature being implemented.
      placeholder: "How do you think this feature should work?"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Provide any additional information or context that may help.
      placeholder: "Any other relevant information or links"
