// This file is auto-generated by the pre-commit hook
// DO NOT EDIT MANUALLY

export const COMMIT_HASH = 'c384527390aa3727e460cdabbcfcda5df3ade0e6';
export const SHORT_COMMIT_HASH = 'c3845273';
export const BUILD_DATE = '2025-08-08T08:21:15Z';

export interface BuildInfo {
  commitHash: string;
  shortCommitHash: string;
  buildDate: string;
}

export const buildInfo: BuildInfo = {
  commitHash: COMMIT_HASH,
  shortCommitHash: SHORT_COMMIT_HASH,
  buildDate: BUILD_DATE,
};
