// This file is auto-generated by the pre-commit hook
// DO NOT EDIT MANUALLY

export const COMMIT_HASH = 'f2a188f91cc29379e99e2b7d1df22ecea81a73a5';
export const SHORT_COMMIT_HASH = 'f2a188f9';
export const BUILD_DATE = '2025-08-08T08:17:10Z';

export interface BuildInfo {
  commitHash: string;
  shortCommitHash: string;
  buildDate: string;
}

export const buildInfo: BuildInfo = {
  commitHash: COMMIT_HASH,
  shortCommitHash: SHORT_COMMIT_HASH,
  buildDate: BUILD_DATE,
};

export const getVersionString = (): string => SHORT_COMMIT_HASH;
