sequenceDiagram
    participant A1 as User A1 (Node A)
    participant NodeA as Node A
    participant NodeB as Node B
    participant B1 as User B1 (Node B)
    participant IPFS as IPFS

    %% Invite creation
    A1->>NodeA: Invite User with Email & Role
    NodeA->>NodeA: Insert USER_PERMISSION
    NodeA->>NodeA: Insert 'invite' EVENT
    NodeA->>IPFS: Write 'invite' EVENT file to every User on the workspace

    %% Remote nodes process invite
    NodeB->>IPFS: Detect new EVENT file
    NodeB->>NodeB: Insert 'invite' USER_PERMISSION
    NodeB->>NodeB: Insert 'invite' EVENT

    %% revoke by inviter
    A1->>NodeA: Revoke permission
    NodeA->>NodeA: INSERT 'removed' event
    NodeA->>NodeA: DELETE USER_PERMISSION
    NodeA->>IPFS: Write 'removed' EVENT file to every User on the workspace
    NodeB->>IPFS: Detect new EVENT file
    NodeB->>NodeB: INSERT 'removed' event
    NodeB->>NodeB: DELETE USER_PERMISSION

    %% self revoke or user (soft/hard) deleted
    B1->>NodeB: Revoke permission
    NodeB->>NodeB: INSERT 'removed' event
    NodeB->>NodeB: DELETE USER_PERMISSION
    NodeB->>IPFS: Write 'removed' EVENT file to every User on the workspace
    NodeA->>IPFS: Detect new EVENT file
    NodeA->>NodeA: INSERT 'removed' event
    NodeA->>NodeA: DELETE USER_PERMISSION

    %% workspace removed
    A1->>NodeA: Remove Workspace
    NodeA->>NodeA: INSERT 'workspace removed' event
    NodeA->>NodeA: DELETE USER_PERMISSION
    NodeA->>IPFS: Write 'removed workspace' EVENT file to every User on the workspace
    NodeB->>IPFS: Detect new EVENT file
    NodeB->>NodeB: INSERT 'removed workspace' event
    NodeB->>NodeB: DELETE USER_PERMISSION

    %% Event already processed
    NodeA->>IPFS: Detect old EVENT file
    NodeA->>NodeA: event id already in DB and marked as processed - ignored