
sequenceDiagram
    participant A1 as User A1 (Node A)
    participant NodeA as Node A
    participant NodeB as Node B
    participant B1 as User B1 (Node B)
    participant IPFS as IPFS

    %% Invite creation
    note over A1,IPFS: User A1 on Node A invites User B1 on Node B to Workspace 1
    A1->>NodeA: Invite User with Email & Role
    NodeA->>NodeA: Insert USER_PERMISSION
    NodeA->>NodeA: Insert 'invite' EVENT
    NodeA->>IPFS: Write 'invite' EVENT file

    %% Remote nodes process invite
    NodeB->>IPFS: Detect new EVENT file
    NodeB->>NodeB: Insert 'invite' USER_PERMISSION
    NodeB->>NodeB: Insert 'invite' EVENT
    NodeB->>B1: Optional notify

    %% Invite revocation by inviter
    A1->>NodeA: Revoke permission
    NodeA->>NodeA: INSERT 'removed' event
    NodeA->>NodeA: DELETE USER_PERMISSION
    NodeA->>IPFS: Write 'removed' EVENT file
    NodeB->>IPFS: Detect new EVENT file
    NodeB->>NodeB: INSERT 'removed' event
    NodeB->>NodeB: DELETE USER_PERMISSION

    %% Self-removal
    B1->>NodeB: Remove self from workspace
    NodeB->>NodeB: INSERT 'removed' event
    NodeB->>NodeB: DELETE USER_PERMISSION
    NodeB->>IPFS: Write 'removed' EVENT file
    NodeA->>IPFS: Detect new EVENT file
    NodeA->>NodeA: INSERT 'removed' event
    NodeA->>NodeA: DELETE USER_PERMISSION

    %% Event already processed
    NodeA->>IPFS: Detect old EVENT file
    NodeA->>NodeA: event id already in DB and marked as processed - ignored

    %% User deleted
    A1->>NodeA: Delete User 1
    NodeA->>NodeA: DELETE USER_PERMISSIONs for User 1
    NodeA->>NodeA: DELETE USER for User 1
    NodeA->>NodeA: INSERT 'user removed' event
    NodeA->>IPFS: Write 'user removed' EVENT file
    NodeB->>IPFS: Detect new EVENT file
    NodeB->>NodeB: DELETE USER_PERMISSIONs for User 1
    NodeB->>NodeB: INSERT 'user removed' event
    
    %% Workspace deleted
    A1->>NodeA: Delete Workspace 1
    NodeA->>NodeA: DELETE USER_PERMISSIONs for Workspace 1
    NodeA->>NodeA: INSERT 'workspace removed' event
    NodeA->>IPFS: Write 'workspace removed' EVENT file
    NodeB->>IPFS: Detect new EVENT file
    NodeB->>NodeB: DELETE USER_PERMISSIONs for Workspace 1
    NodeB->>NodeB: INSERT 'workspace removed' event