services:
  ##################################################################################
  ## Open WebIU Ollama             #################################################
  ##################################################################################
  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - ${OPEN_WEBUI_PORT}:8080
    environment:
      ENV: prod
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
      ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL}
      ADMIN_USER_PASSWORD: ${ADMIN_USER_PASSWORD}
      SPACE_ID: "true" # truthy value allows setting of admin credentials ^^^
    volumes:
      - ../../volumes/open-webui:/app/backend/data
    depends_on:
      - ollama

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - 11434:11434/tcp
    healthcheck:
      test: ollama --version || exit 1
    environment:
      OLLAMA_DEBUG: 1
    command: serve
    volumes:
      - ../../volumes/ollama:/root/.ollama
