// This file is auto-generated by the pre-commit hook
// DO NOT EDIT MANUALLY

export const COMMIT_HASH = '877eca3dfad6e8d532a2a1e0391c0f85e11f4510';
export const SHORT_COMMIT_HASH = '877eca3d';
export const BUILD_DATE = '2025-08-08T08:13:18Z';

export interface BuildInfo {
  commitHash: string;
  shortCommitHash: string;
  buildDate: string;
}

export const buildInfo: BuildInfo = {
  commitHash: COMMIT_HASH,
  shortCommitHash: SHORT_COMMIT_HASH,
  buildDate: BUILD_DATE,
};

export const getVersionString = (): string => SHORT_COMMIT_HASH;
